export const baseUrl = "https://shopify-e-commerce-backend-1.onrender.com"
export const signUpUrl = "/users/signup"
export const loginUrl = "/users/login"
export const getUserUrl = "/users/"
export const logoutUrl = "/users/logout"
export const updateUrl = "/users/update"